### ISSUE TITLE
Android 14 Messenger crashes

### ISSUE THREAD

**Issue by Yoanndp** [Xposed-Modules-Repo/app.neonorbit.chatheadenabler#2]
Hello, I just updated my Pixel 7 from Android 13 to Android 14, and Messenger is crashing and disconnecting me at least twice a day. Can you please check if you could fix it? I tried deleting app data and cache, and also uninstalling and reinstalling the app, but it keeps crashing.

This is the crash log:
```LOGCAT
FATAL EXCEPTION: main
Process: com.facebook.orca, PID: 16740
java.lang.RuntimeException: Unable to create service com.facebook.messaging.chatheads.service.ChatHeadService: java.lang.SecurityException: Starting FGS with type microphone callerApp=ProcessRecord{ac7bedf 16740:com.facebook.orca/u0a514} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MICROPHONE] any of the permissions allOf=false [android.permission.CAPTURE_AUDIO_HOTWORD, android.permission.CAPTURE_AUDIO_OUTPUT, android.permission.CAPTURE_MEDIA_OUTPUT, android.permission.CAPTURE_TUNER_AUDIO_INPUT, android.permission.CAPTURE_VOICE_COMMUNICATION_OUTPUT, android.permission.RECORD_AUDIO]  and the app must be in the eligible state/exemptions to access the foreground only permission
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4664)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2264)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.SecurityException: Starting FGS with type microphone callerApp=ProcessRecord{ac7bedf 16740:com.facebook.orca/u0a514} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MICROPHONE] any of the permissions allOf=false [android.permission.CAPTURE_AUDIO_HOTWORD, android.permission.CAPTURE_AUDIO_OUTPUT, android.permission.CAPTURE_MEDIA_OUTPUT, android.permission.CAPTURE_TUNER_AUDIO_INPUT, android.permission.CAPTURE_VOICE_COMMUNICATION_OUTPUT, android.permission.RECORD_AUDIO]  and the app must be in the eligible state/exemptions to access the foreground only permission
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
	at java.lang.reflect.Method.invoke(Native Method)
	at X.01E.A01(:8)
	at X.01E.invoke(:37)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy5.setServiceForeground(Unknown Source)
	at android.app.Service.startForeground(Service.java:862)
	at X.3hZ.A00(Unknown Source:207)
	at com.facebook.messaging.chatheads.service.ChatHeadService.A01(Unknown Source:37)
	at com.facebook.messaging.chatheads.service.ChatHeadService.A0P(Unknown Source:276)
	at X.2zF.A0L(Unknown Source:47)
	at X.0IP.onCreate(:51)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4651)
	... 9 more
```

From what I understood, the crash occurred because the app attempted to start a foreground service (ChatHeadService) with microphone permissions, but it lacked the necessary permissions to do so. As a result, the service could not be created, leading to the crash of the Messenger app. I double-checked, but the Messenger app has all the required permissions (in this case Camera, Microphone, Notifications, and Gallery).

**Comment by Yoanndp** [comment]
Issue handled [there](https://github.com/NeonOrbit/ChatHeadEnabler/issues/15).
